spring.datasource.url=jdbc:postgresql://localhost:5432/vocabulary_db
spring.datasource.username=postgres
spring.datasource.password=CYV94XpcfV
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

mybatis.configuration.map-underscore-to-camel-case=true

spring.thymeleaf.cache=false
