# TODO: 接続情報を設定してください（データベース名：wordapp）
spring.datasource.url=jdbc:postgresql://____________:____________/____________
spring.datasource.username=____________
spring.datasource.password=____________

# ドライバー（変更不要）
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis設定（変更不要）
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.wordapp.model
